### ISSUE TITLE
Linking C executable bin/quiet_encode_soundcard failed

### ISSUE THREAD

**Issue by andreicociuba** [quiet/quiet#10] opened 2016-06-15 13:01 UTC
running the bootstrap file in quiet/quiet halts.

this is the error message.

[ 42%] Linking C executable bin/quiet_encode_soundcard
/usr/bin/ld: lib/libquiet_static.a(encoder.c.o): undefined reference to symbol 'ceilf@@GLIBC_2.0'
//lib/i386-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/quiet_encode_soundcard.dir/build.make:95: recipe for target 'bin/quiet_encode_soundcard' failed
make[2]: *** [bin/quiet_encode_soundcard] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/quiet_encode_soundcard.dir/all' failed
make[1]: *** [CMakeFiles/quiet_encode_soundcard.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

apparently other people having the error " error adding symbols: DSO missing from command line" fixed it by adding the libraries in a different order, or specifying some or other compiler flag in the makefile, but it varies a lot, and I don't know exactly what their solutions actually do, and if/how they apply to quiet.
unfortunately the compiling process with cmake is a bit too complex for me, as i only ever compiled my own code without resorting to makefiles or similar. (i am a very unskilled coder as far as coders go, and never had to code proffesionally, so i get by with whatever i can make work).

I can provide any other additional information on request.

running a fresh install of ubuntu 16.04 with all dependencies installed.

**Comment by brian-armstrong** [comment] 2016-06-15 19:28
I was able to reproduce this. It looks like with gcc you have to explicitly link in libm for math functions. Clang is lenient enough to just assume/know I want that, so it didn't complain.

I pushed a fix for that and I can now build the portaudio binding in Ubuntu

**Comment by andreicociuba** [comment] 2016-06-15 19:32
Thanks a million, I am eager to try it out. Don't close the issue yet, I
will check back to confirm the fix pretty soon when I get to my own
computer.

**Comment by andreicociuba** [comment] 2016-06-15 19:47
yes, fixed, it does compile

**Closed** 2016-06-15 20:24 UTC
